/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial2;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import parcial2.Model.Persona;
import parcial2.Util.PerformanceMonitor;
import parcial2.Util.SpatialEfficiency;
import parcial2.Util.ApiDataFetcher;
import com.google.gson.JsonObject;
import java.util.List;

public class App {

    public static final Logger logger = LogManager.getLogger(App.class);

    public static void main(String[] args) throws Exception {
        PerformanceMonitor monitor = new PerformanceMonitor("App Main Process");
        monitor.inicio();
        Persona persona = new Persona("Juan Perez", 30);
        logger.info("Hello World!");
        logger.info("This is a log message.");

        for (int i = 0; i < 5; i++) {
            logger.debug("Debug message number: " + i);
        }
        monitor.finalizado();
        System.out.println(SpatialEfficiency.medirPesoObjeto(persona));

        // Prueba de ApiDataFetcher
        List<JsonObject> datos = ApiDataFetcher.fetchDefaultData();
        for (JsonObject obj : datos) {
            System.out.println(obj);
        }
    }
}

